#!/bin/sh
set -e
# Automatically added by dh_installinit/13.14.1ubuntu5
if [ "$1" = "remove" ] && [ -x "/etc/init.d/mongod" ] ; then
	chmod -x "/etc/init.d/mongod" >/dev/null || true
fi
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d mongod remove >/dev/null
fi
# End automatically added section
